### PR TITLE
Added translation support

### PR DESCRIPTION
**Pull request by Blueberryy**
+extra special Russian translation from starter kit

### CODE REVIEW

**Comment by mmaulwurff** [comment]
I'm merging this, though I'll fix formatting and change string names.

Thanks!

**Comment by mmaulwurff** [comment]
> +extra special Russian translation from starter kit

Didn't get this part.

**Comment by Blueberryy** [comment]
oh. i don't know, it's exist on my repo but not uploaded for some reason

**Comment by mmaulwurff** [comment]
What's the full file name? my .gitignore ignores everything that is not .txt, .md, .zs, and .sh.

**Pull request merged**
